In [4]:
import pandas as pd
ac = pd.read_csv(r'C:\Users\parkm\Desktop\data\1\trans_to_csv\acoustic\aco_0Nm_BPFI_03.csv')
ac.head()

,Time_s,Signal_x_values_start_value,Signal_x_values_increment,Signal_x_values_number_of_values,Signal_x_values_quantity_label,Signal_x_values_quantity_unit_transformation_offset,Signal_x_values_quantity_unit_transformation_factor,Signal_x_values_quantity_unit_transformation_log_reference,Signal_x_values_quantity_quantity_terms_1_num,Signal_x_values_quantity_quantity_terms_1_den,...,Signal_function_record_average_nr_of_averages,Signal_function_record_average_type,Signal_function_record_average_parameter,Signal_function_record_TL_export_properties_annotation_project_name,Signal_function_record_TL_export_properties_annotation_section_name,Signal_function_record_TL_export_properties_annotation_run_name,Signal_function_record_TL_export_properties_annotation_absolute_time,Signal_function_record_TL_export_properties_annotation_channel_group,Signal_function_record_TL_export_properties_annotation_orig_location,Pa_Col1
0,0.000003,0.000003,0.00002,3072000,s,0,1,1,0,1,...,0,UNKNOWN,0,Test1,Section1,210705_Inner_0.3mm_5cm,2021-07-05 16:03:30 ms 869.785,Acoustic,C:\PHM\Testbed\Test1\Section1\210705_Inner_0.3...,0.041553
1,0.000023,0.000003,0.00002,3072000,s,0,1,1,0,1,...,0,UNKNOWN,0,Test1,Section1,210705_Inner_0.3mm_5cm,2021-07-05 16:03:30 ms 869.785,Acoustic,C:\PHM\Testbed\Test1\Section1\210705_Inner_0.3...,0.091455
2,0.000042,0.000003,0.00002,3072000,s,0,1,1,0,1,...,0,UNKNOWN,0,Test1,Section1,210705_Inner_0.3mm_5cm,2021-07-05 16:03:30 ms 869.785,Acoustic,C:\PHM\Testbed\Test1\Section1\210705_Inner_0.3...,0.173804
3,0.000062,0.000003,0.00002,3072000,s,0,1,1,0,1,...,0,UNKNOWN,0,Test1,Section1,210705_Inner_0.3mm_5cm,2021-07-05 16:03:30 ms 869.785,Acoustic,C:\PHM\Testbed\Test1\Section1\210705_Inner_0.3...,0.241284
4,0.000081,0.000003,0.00002,3072000,s,0,1,1,0,1,...,0,UNKNOWN,0,Test1,Section1,210705_Inner_0.3mm_5cm,2021-07-05 16:03:30 ms 869.785,Acoustic,C:\PHM\Testbed\Test1\Section1\210705_Inner_0.3...,0.345874

In [8]:
ac_selected = ac.iloc[:, [0, -1]]
ac_selected.head()

     Time_s   Pa_Col1
0  0.000003  0.041553
1  0.000023  0.091455
2  0.000042  0.173804
3  0.000062  0.241284
4  0.000081  0.345874

In [ ]:
ct= pd.read_csv(r'C:\Users\parkm\Desktop\data\1\trans_to_csv\cur,temp\ct_0Nm_BPFI_03.csv')
ct.head()

,cDAQ9185-1F486B5Mod1/ai0,cDAQ9185-1F486B5Mod1/ai1,cDAQ9185-1F486B5Mod2/ai0,cDAQ9185-1F486B5Mod2/ai2,cDAQ9185-1F486B5Mod2/ai3
0,27.607992,28.217591,1.894377,0.949463,-2.165271
1,27.607992,28.217591,2.128889,0.926111,-2.309938
2,27.607992,28.217591,2.373001,0.882154,-2.526938
3,27.607992,28.217591,2.087747,1.193974,-2.444867
4,27.607992,28.217591,2.393572,1.125291,-2.718899

In [9]:
vib=pd.read_csv(r'C:\Users\parkm\Desktop\data\1\trans_to_csv\vibration\vib_0Nm_BPFI_03.csv')
vib.head()

,Time_s,Signal_x_values_start_value,Signal_x_values_increment,Signal_x_values_number_of_values,Signal_x_values_quantity_label,Signal_x_values_quantity_unit_transformation_offset,Signal_x_values_quantity_unit_transformation_factor,Signal_x_values_quantity_unit_transformation_log_reference,Signal_x_values_quantity_quantity_terms_1_num,Signal_x_values_quantity_quantity_terms_1_den,...,Signal_function_record_TL_export_properties_annotation_channel_group_3,Signal_function_record_TL_export_properties_annotation_channel_group_4,Signal_function_record_TL_export_properties_annotation_orig_location_1,Signal_function_record_TL_export_properties_annotation_orig_location_2,Signal_function_record_TL_export_properties_annotation_orig_location_3,Signal_function_record_TL_export_properties_annotation_orig_location_4,g_Col1,g_Col2,g_Col3,g_Col4
0,0.000012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,-8.947968,14.536224,-1.054167,0.969664
1,0.000051,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.321366,-2.065806,-1.840423,3.046795
2,0.000090,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.273554,2.071666,-0.860117,2.146393
3,0.000129,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,-7.890409,15.446308,-0.465193,1.381279
4,0.000168,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,-1.295177,-0.780089,0.003352,-0.305207

In [ ]:
vib_selected = vib.iloc[:, [0] + list(range(vib.shape[1]-4, vib.shape[1]))]
vib_selected.head() 
#모델 학습에는 일관성 유지를 위해 베어링 하우징 A의 x축 방향 가속도 데이터만을 사용하였다. -> Time_s랑 g_Col1만 WDCNN에 쓴 듯

     Time_s    g_Col1     g_Col2    g_Col3    g_Col4
0  0.000012 -8.947968  14.536224 -1.054167  0.969664
1  0.000051  2.321366  -2.065806 -1.840423  3.046795
2  0.000090  0.273554   2.071666 -0.860117  2.146393
3  0.000129 -7.890409  15.446308 -0.465193  1.381279
4  0.000168 -1.295177  -0.780089  0.003352 -0.305207

In [15]:
ac_selected.head()

     Time_s   Pa_Col1
0  0.000003  0.041553
1  0.000023  0.091455
2  0.000042  0.173804
3  0.000062  0.241284
4  0.000081  0.345874

In [16]:
ct.head()

,cDAQ9185-1F486B5Mod1/ai0,cDAQ9185-1F486B5Mod1/ai1,cDAQ9185-1F486B5Mod2/ai0,cDAQ9185-1F486B5Mod2/ai2,cDAQ9185-1F486B5Mod2/ai3
0,27.607992,28.217591,1.894377,0.949463,-2.165271
1,27.607992,28.217591,2.128889,0.926111,-2.309938
2,27.607992,28.217591,2.373001,0.882154,-2.526938
3,27.607992,28.217591,2.087747,1.193974,-2.444867
4,27.607992,28.217591,2.393572,1.125291,-2.718899

In [14]:
df1=pd.merge(ac_selected, vib_selected, on='Time_s', how='outer')
df1.head(13)

      Time_s   Pa_Col1    g_Col1     g_Col2    g_Col3    g_Col4
0   0.000003  0.041553       NaN        NaN       NaN       NaN
1   0.000012       NaN -8.947968  14.536224 -1.054167  0.969664
2   0.000023  0.091455       NaN        NaN       NaN       NaN
3   0.000042  0.173804       NaN        NaN       NaN       NaN
4   0.000051       NaN  2.321366  -2.065806 -1.840423  3.046795
5   0.000062  0.241284       NaN        NaN       NaN       NaN
6   0.000081  0.345874       NaN        NaN       NaN       NaN
7   0.000090       NaN  0.273554   2.071666 -0.860117  2.146393
8   0.000101  0.476025       NaN        NaN       NaN       NaN
9   0.000121  0.522192       NaN        NaN       NaN       NaN
10  0.000129       NaN -7.890409  15.446308 -0.465193  1.381279
11  0.000140  0.479395       NaN        NaN       NaN       NaN
12  0.000160  0.476489       NaN        NaN       NaN       NaN